version: "3.8"
services:
  local-rabbitmq:
    hostname: local-rabbitmq
    image: 'rabbitmq-inited:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=password
    volumes:
      - 'rabbitmq_data:/bitnami'
volumes:
    rabbitmq_data:
      driver: local
